name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build
        run: |
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for trusted publishing (preferred) or use API token below
      contents: read
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        if: ${{ github.ref_type == 'tag' }}

      # If you prefer API token instead of Trusted Publishing, uncomment below and add PYPI_API_TOKEN secret
      # - name: Publish to PyPI (API token)
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     packages-dir: dist/
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #   if: ${{ github.ref_type == 'tag' }}